#define DSS_PRIV_FILENAME "/tmp/dropbear_dss_host_key"
#define RSA_PRIV_FILENAME "/tmp/dropbear_rsa_host_key"
#define ECDSA_PRIV_FILENAME "/tmp/dropbear_ecdsa_host_key"
#define ED25519_PRIV_FILENAME "/tmp/dropbear_ed25519_host_key"
#define DROPBEAR_PIDFILE "/tmp/dropbear.pid"
